import type { MDXComponents } from "mdx/types";
import {
  TheoryBox,
  TeacherNote,
  ForStudents,
  ForParents,
  Sources,
  KeyTakeaways,
  CommonMisconception,
  ActionChecklist,
  RelatedConcepts,
  ReflectionPrompt,
  WhyItMatters,
  RelatedGuides,
  WhenToUse,
  Troubleshooting,
  PrintableBlock,
  BookOverview,
  WhoThisIsFor,
  WhatYouWillLearn,
  TopicIntro,
  RelatedCards,
} from "@/components/mdx";
import { toImageUrl } from "@/lib/image-url";

export const mdxComponents: MDXComponents = {
  img: (props) => <img {...props} src={toImageUrl(props.src ?? "")} alt={props.alt ?? ""} />,
  RelatedCards,
  TheoryBox,
  TeacherNote,
  ForStudents,
  ForParents,
  Sources,
  SourceNote: Sources,
  KeyTakeaways,
  CommonMisconception,
  ActionChecklist,
  RelatedConcepts,
  ReflectionPrompt,
  WhyItMatters,
  RelatedGuides,
  WhenToUse,
  Troubleshooting,
  PrintableBlock,
  BookOverview,
  WhoThisIsFor,
  WhatYouWillLearn,
  TopicIntro,
};
